name: Deploy Web SalaG

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # Single deploy job since we're just deploying
  deploy:
  
    runs-on: ubuntu-latest

    
    steps:
      - name: Acesso EC2
        run: |
           echo "$KEY_G" > webserver && chmod 600 webserver
           ssh -o StrictHostKeyChecking=no -i "webserver" ubuntu@ec2-54-243-52-244.compute-1.amazonaws.com "
               cd /var/www/html &&
               git pull "
               
